---
- name: Install coturn
  apt:
    name: coturn
    update_cache: true
    state: present

- name: Make shure, coturn directory exists
  file:
    path: /etc/coturn
    mode: 0755
    owner: root
    group: root
    state: directory
  notify: restart coturn

- name: Make shure, coturn cert directory exists
  file:
    path: /etc/coturn/certs
    mode: 0700
    owner: turnserver
    group: turnserver
    state: directory
  notify: restart coturn

- name: Copy existing certs
  become_user: root
  become: yes
  copy:
    remote_src: yes
    src: "/etc/letsencrypt/live/{{ nginx_domain }}/{{ item }}"
    dest: "/etc/coturn/certs/{{ item }}"
  with_items:
    - "privkey.pem"
    - "fullchain.pem"

- name: Copy systemd coturn unit
  template:
    src: "coturn.service"
    dest: /etc/systemd/system/coturn.service
  notify: restart coturn

- name: Copy coturn config-file
  template:
    src: "turnserver.conf.j2"
    dest: /etc/turnserver.conf
  notify: restart coturn

- name: Enable coturn server in defaults
  lineinfile:
    path: /etc/default/coturn
    regexp: 'TURNSERVER_ENABLED'
    line: 'TURNSERVER_ENABLED=1'
  notify: restart coturn

- name: Ensure coturn is started
  systemd:
    name: coturn
    state: started
    enabled: true

- name: Ensure coturn is restarted everyday @ 4 am
  cron:
    name: "restart coturn"
    minute: "0"
    hour: "4"
    user: root
    job: "systemctl restart coturn.service"
