---
- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ turn_hostname }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Generate Certificates
  command: certbot certonly -d {{ turn_hostname }} --agree-tos --email {{ letsencrypt_email }} --standalone
  when: not certbot_certificate_file_path.stat.exists
