---
- name: Install required packages
  apt:
    name: "{{ bbb_required_packages }}"
    update_cache: true
    state: present

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: repositories.yml

- name: install bbb and dependencies
  apt:
    name: "{{ bbb_and_dependencies }}"
    state: latest
  register: _bbb_install

- import_tasks: mongodb.yml

- meta: flush_handlers

- name: Ensure mongod is started and enabled to start at boot.
  service:
    name: mongod
    enabled: true
    state: started

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    enabled: true
    state: started

- import_tasks: config.yml
