---
- name: Ensure nginx ppa is used for newer nginx versions
  apt_repository:
    repo: ppa:nginx/stable
  register: nginx_repo

- name: Ensure nginx from ppa is pinned
  copy:
    content: |
      Package: *
      Pin: release n=xenial,o=LP-PPA-nginx-stable
      Pin-Priority: 1000
    dest: /etc/apt/preferences.d/ppa-nginx
    mode: 0755
  register: nginx_ppa_pin

- name: Ensure apt cache gets updated
  apt:
    update_cache: yes
  when: nginx_repo.changed or nginx_ppa_pin.changed

- name: Ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure nginx installed and current version
  apt:
    name: nginx
    state: latest
  notify: restart nginx

- name: Ensure nginx ufw configuration is available
  copy:
    # this is the standard config from the nginx package(?)
    # space character in the rule name is not that nice, but whatever
    content: |
      [Nginx HTTP]
      title=Web Server (Nginx, HTTP)
      description=Small, but very powerful and efficient web server
      ports=80/tcp

      [Nginx HTTPS]
      title=Web Server (Nginx, HTTPS)
      description=Small, but very powerful and efficient web server
      ports=443/tcp

      [Nginx Full]
      title=Web Server (Nginx, HTTP + HTTPS)
      description=Small, but very powerful and efficient web server
      ports=80,443/tcp
    mode: 0644
    dest: /etc/ufw/applications.d/nginx

- name: Allow nginx in ufw
  ufw:
    rule: allow
    name: Nginx Full
    state: enabled

- name: Enusre nginx has the right config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Ensure http config exists
  template:
    src: http.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_config_name }}-http.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Ensure http config is applied
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ nginx_config_name }}-http.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_config_name }}-http.conf"
  notify: reload nginx

- name: Ensure nginx subconfig folder exists
  file:
    path: "/etc/nginx/{{ nginx_config_name }}.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: reload nginx

- name: Ensure existence of maintenance folder
  file:
    path: /var/www/html/maintenance
    state: directory

- name: Copy maintenance files
  copy:
    src: "{{item}}"
    dest: "/var/www/html/maintenance/{{item}}"
  with_items:
    - index.html
    - hackhack.gif
