---
- name: Register certbot certificate file
  stat:
    path: "/etc/letsencrypt/live/{{ nginx_domain }}/fullchain.pem"
  register: certbot_certificate_file_path

- name: Ensure folder for letsencrypt exists
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Generate Certificates
  command: certbot certonly --webroot --webroot-path /var/www/letsencrypt -d {{ nginx_domain }}{% for alias in nginx_alias %} -d {{ alias }}{% endfor %} --agree-tos --email {{ letsencrypt_email }} -n
  notify: reload nginx
  when: not certbot_certificate_file_path.stat.exists

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Ensure https config exists
  template:
    src: https.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_config_name }}-https.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- name: Ensure https config is applied
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ nginx_config_name }}-https.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_config_name }}-https.conf"
  notify: reload nginx
