{
 "title": "BigBlueButton Server Instance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Active Meetings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Participants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Selected timeframe"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "CPU Utilization vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=\"$instance\"}[5m])) * 100)",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "Type of Users Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "bbb_meetings_listeners{instance=\"$instance\"}",
     "legendFormat": "Listeners"
    },
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice"
    },
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "Bandwidth vs. Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "bps", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "Bandwidth out"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "Bandwidth in"
    },
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "(Participants - Listeners) Delta",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants - bbb_meetings_listeners{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_recordings_processing{instance=\"$instance\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "bbb_recordings_processed{instance=\"$instance\"}",
     "legendFormat": "Processed"
    },
    {
     "expr": "bbb_recordings_published{instance=\"$instance\"}",
     "legendFormat": "Published"
    },
    {
     "expr": "bbb_recordings_unpublished{instance=\"$instance\"}",
     "legendFormat": "Unpublished"
    },
    {
     "expr": "bbb_recordings_deleted{instance=\"$instance\"}",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "bbb_meetings_participants{instance=\"$instance\"}",
     "legendFormat": "Meeting Participants"
    },
    {
     "expr": "bbb_meetings_voice_participants{instance=\"$instance\"}",
     "legendFormat": "Voice Participants"
    },
    {
     "expr": "bbb_meetings_video_participants{instance=\"$instance\"}",
     "legendFormat": "Video Participants"
    },
    {
     "expr": "(bbb_meetings_participants{instance=\"$instance\"} + bbb_meetings_voice_participants{instance=\"$instance\"} + bbb_meetings_video_participants{instance=\"$instance\"})",
     "legendFormat": "All Participants"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "API 95-th Percentile Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Latency [s]" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getMeetings"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processing\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getRecordings processing"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=processed\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getRecordings processed"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=published\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getRecordings published"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=unpublished\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getRecordings unpublished"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{endpoint=\"getRecordings\", parameters=\"state=deleted\", instance=\"$instance\"}[5m])) by (le, instance))",
       "legendFormat": "getRecordings deleted"
      }
     ]
    }
   ]
  }
 ]
}