- name: Ensure pip is installed
  become: true
  apt:
    name:
      - python3-pip
    state: present

- name: Create a file with all trusted ca's
  become: true
  assemble:
    src: /usr/share/ca-certificates/mozilla
    dest: /usr/share/trusted-cas.crt
    mode: 644
    owner: root
    group: root

- name: update pip
  become: true
  pip:
    name: pip==20.3.3
    state: present
    extra_args: --cert /usr/share/trusted-cas.crt
