---
- name: Ensure group "greenlight" exists
  group:
    name: greenlight
    state: present

- name: Ensure user greenlight exists
  user:
    name: greenlight
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: greenlight
    state: present

- name: Checkout greenlight repository
  git:
    repo: https://github.com/ORI-s-Source/greenlight
    dest: /var/www/greenlight
    version: release-2.7.14-2
    force: yes
  notify:
    - restart greenlight
    - reload nginx

- name: Ensure greenlight is owner of /var/www/greenlight
  file:
    path: /var/www/greenlight
    recurse: yes
    owner: greenlight
    group: greenlight

- name: Ensure Bundler 2 is installed
  gem:
    name: bundler
    state: latest
    user_install: no

- name: Ensure sqlite is installed
  apt:
    name:
      - sqlite3
      - libsqlite3-dev
    state: present

# bundler: deployment mode by cli argument is deprecated, so we're going to run this:
- name: Ensure bundle in is deployment mode
  command:
    cmd: bundle config set deployment 'true'
    chdir: /var/www/greenlight
    creates: /var/www/greenlight/.bundle/config
  become: yes
  become_user: greenlight

- name: Ensure gems for greenlight are installed
  bundler:
    state: present
    exclude_groups:
      - development
      - test
      - assets
    chdir: /var/www/greenlight
  become: yes
  become_user: greenlight

- name: Ensure environment file for greenlight
  template:
    src: env.j2
    dest: /var/www/greenlight/.env

- name: make sure the .env is owned by greenlight
  file:
    path: /var/www/greenlight/.env
    owner: greenlight
    group: greenlight

- name: Ensure systemd unit for greenlight
  template:
    src: greenlight.service
    dest: /etc/systemd/system/greenlight.service

- name: Enable greenlight units
  systemd:
    daemon_reload: yes
    name: greenlight
    enabled: yes

- name: Ensure greenlight is started
  systemd:
    name: greenlight
    state: started

- name: Ensure greenlight nginx config exists
  template:
    src: nginx-greenlight.conf.j2
    dest: /etc/nginx/{{ nginx_config_name }}.d/greenlight.conf
  notify: reload nginx
